language: go
sudo: false
go:
- 1.16.x
- 1.17.x
- master
go_import_path: github.com/lindaprotocol/grpc-gateway
cache:
  directories:
  - $HOME/local
  - ${TRAVIS_BUILD_DIR}/examples/browser/node_modules
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

services:
  - docker
  - postgresql
  - redis-server

before_install:
- ./.travis/install-protoc.sh 3.15.0
- ./.travis/install-swagger-codegen.sh 2.4.15
- nvm install v14 && nvm use v14 && node --version
- go get github.com/golang/lint/golint
- go get github.com/dghubble/sling
- go get github.com/go-resty/resty
- go mod download

install:
- go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
- go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
- go install github.com/golang/protobuf/protoc-gen-go

before_script:
- psql -c 'create database lindascan_test;' -U postgres
- sh -c 'cd examples/browser && npm install'

script:
- make realclean && make examples SWAGGER_CODEGEN="java -jar $HOME/local/swagger-codegen-cli.jar"
- make generate
- go build -v ./...
- go test -v -race ./...
- make lint
- sh -c 'cd examples/browser && node ./node_modules/gulp/bin/gulp'

after_success:
- bash <(curl -s https://codecov.io/bash)

env:
  global:
  - "PATH=$PATH:$HOME/local/bin"
  - GO_VERSION_TO_DIFF_TEST="go version go1\.17\.[0-9]\+ linux/amd64"
  - GO111MODULE=on
  matrix:
  - GATEWAY_PLUGIN_FLAGS=
  - GATEWAY_PLUGIN_FLAGS=request_context=false